### ISSUE TITLE
Potential global state issue

### ISSUE THREAD

**Issue by chuwik** [Fatheed7/FM#14]
Repro steps:
1. Open the [deployed website](https://fm-recruitment-2ac38cc99aa0.herokuapp.com/)
2. Don't choose any file, click 'Upload'

Expected: nothing is returned, as I haven't uploaded any file yet.
Actual: I see results, maybe from a file someone else uploaded?

I have only been able to repro this once, the app is down now so can't test further. Random guess but wondering if global state could be the issue with concurrent users.

**Comment by HarrisonRClark** [comment]
Thank you for the feedback!

We're going to look into using session states instead of global.

**Comment by HarrisonRClark** [comment]
We had to roll back the previous change so opening this again
